--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4 (Debian 16.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.3

-- Started on 2024-09-06 17:50:12 +0530

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 247 (class 1259 OID 18484)
-- Name: Admins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Admins" (
                                 "AdminId" integer NOT NULL,
                                 "Email" text NOT NULL,
                                 "Name" text NOT NULL,
                                 "Password" text NOT NULL
);


ALTER TABLE public."Admins" OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 18483)
-- Name: Admins_AdminId_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Admins" ALTER COLUMN "AdminId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Admins_AdminId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 18382)
-- Name: Businesses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Businesses" (
                                     "Id" integer NOT NULL,
                                     "NameOfBusiness" character varying(100) NOT NULL,
                                     "AddressOfBusiness" character varying(255) NOT NULL,
                                     "RegistrationNumber" character varying(100) NOT NULL,
                                     "SharesOwned" character varying(50) NOT NULL,
                                     "ResidenceVisaInfoId" integer NOT NULL
);


ALTER TABLE public."Businesses" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 18381)
-- Name: Businesses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Businesses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Businesses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 18269)
-- Name: Childrens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Childrens" (
                                    "Id" integer NOT NULL,
                                    "Name" character varying(100) NOT NULL,
                                    "Gender" text NOT NULL,
                                    "PlaceOfBirth" text NOT NULL,
                                    "UserInfoId" integer NOT NULL
);


ALTER TABLE public."Childrens" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 18268)
-- Name: Childrens_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Childrens" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Childrens_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 18282)
-- Name: EmergencyContacts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EmergencyContacts" (
                                            "Id" integer NOT NULL,
                                            "Name" character varying(100) NOT NULL,
                                            "Address" character varying(255) NOT NULL,
                                            "Contact" character varying(20) NOT NULL,
                                            "Relationship" character varying(50),
                                            "UserInfoId" integer NOT NULL,
                                            "SpendableAmount" double precision DEFAULT 0.0 NOT NULL,
                                            "Support" text,
                                            "UsdAmount" double precision DEFAULT 0.0 NOT NULL,
                                            "nameOfCreditCard" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."EmergencyContacts" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 18281)
-- Name: EmergencyContacts_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EmergencyContacts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EmergencyContacts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 18358)
-- Name: EntryVisaApprovals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EntryVisaApprovals" (
                                             "Id" integer NOT NULL,
                                             "VisaNumber" character varying(50) NOT NULL,
                                             "DateIssued" timestamp with time zone NOT NULL,
                                             "Purpose" character varying(50) NOT NULL,
                                             "EntryVisaInfoId" integer NOT NULL
);


ALTER TABLE public."EntryVisaApprovals" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 18357)
-- Name: EntryVisaApprovals_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EntryVisaApprovals" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EntryVisaApprovals_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 18293)
-- Name: EntryVisaInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EntryVisaInfos" (
                                         "Id" integer NOT NULL,
                                         "ObjectOfVisit" character varying(50) NOT NULL,
                                         "ModeOfTravel" character varying(50) NOT NULL,
                                         "DateOfLeaving" timestamp with time zone NOT NULL,
                                         "LastPlaceOfResidence" character varying(100) NOT NULL,
                                         "DateOfIssue" timestamp with time zone NOT NULL,
                                         "ResidenceVisaNumber" character varying(50) NOT NULL,
                                         "HasRefusedVisa" text NOT NULL,
                                         "UserInfoId" integer NOT NULL,
                                         "LastObtainedVisa" text DEFAULT ''::text NOT NULL,
                                         "PeriodOfValidity" integer DEFAULT 0 NOT NULL,
                                         "PeriodOfVisitVisa" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."EntryVisaInfos" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 18292)
-- Name: EntryVisaInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EntryVisaInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EntryVisaInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 18303)
-- Name: NaturalizationInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."NaturalizationInfos" (
                                              "UserInfoId" integer NOT NULL,
                                              "IsNaturalized" boolean NOT NULL,
                                              "NaturalizationDate" timestamp with time zone,
                                              "PlaceOfNaturalization" character varying(100) NOT NULL,
                                              "FormerNationality" character varying(50) NOT NULL,
                                              id integer NOT NULL
);


ALTER TABLE public."NaturalizationInfos" OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 18422)
-- Name: NaturalizationInfos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."NaturalizationInfos" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."NaturalizationInfos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 18313)
-- Name: Passports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Passports" (
                                    "UserInfoId" integer NOT NULL,
                                    "Number" character varying(20) NOT NULL,
                                    "PlaceOfIssue" character varying(100) NOT NULL,
                                    "DateOfIssue" timestamp with time zone NOT NULL,
                                    "DateOfExpiry" timestamp with time zone NOT NULL,
                                    "Id" integer NOT NULL,
                                    "PreviousDateOfExpiry" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
                                    "PreviousDateOfIssue" timestamp with time zone DEFAULT '-infinity'::timestamp with time zone NOT NULL,
                                    "PreviousNumber" text DEFAULT ''::text NOT NULL,
                                    "PreviousPlaceOfIssue" character varying(100) DEFAULT ''::character varying NOT NULL
);


ALTER TABLE public."Passports" OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 18418)
-- Name: Passports_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Passports" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Passports_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 18324)
-- Name: Professions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Professions" (
                                      "Id" integer NOT NULL,
                                      "NameOfWorkplace" character varying(100) NOT NULL,
                                      "AddressOfWorkplace" character varying(255) NOT NULL,
                                      "Email" character varying(100) NOT NULL,
                                      "Fax" character varying(20) NOT NULL,
                                      "UserInfoId" integer NOT NULL
);


ALTER TABLE public."Professions" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 18323)
-- Name: Professions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Professions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Professions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 18395)
-- Name: ResidenceVisaApprovals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ResidenceVisaApprovals" (
                                                 "Id" integer NOT NULL,
                                                 "VisaNumber" character varying(50) NOT NULL,
                                                 "DateIssued" timestamp with time zone NOT NULL,
                                                 "Purpose" character varying(50) NOT NULL,
                                                 "ResidenceVisaInfoId" integer NOT NULL
);


ALTER TABLE public."ResidenceVisaApprovals" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 18394)
-- Name: ResidenceVisaApprovals_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ResidenceVisaApprovals" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ResidenceVisaApprovals_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 18335)
-- Name: ResidenceVisaInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ResidenceVisaInfos" (
                                             "Id" integer NOT NULL,
                                             "DateOfArrival" timestamp with time zone NOT NULL,
                                             "ReasonForApplyingVisa" character varying(255) NOT NULL,
                                             "ApplyingFor" character varying(50) NOT NULL,
                                             "SalaryIncome" text NOT NULL,
                                             "UserInfoId" integer NOT NULL
);


ALTER TABLE public."ResidenceVisaInfos" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 18334)
-- Name: ResidenceVisaInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ResidenceVisaInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ResidenceVisaInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 18347)
-- Name: SpouseInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SpouseInfos" (
                                      "UserInfoId" integer NOT NULL,
                                      "Fullname" character varying(100) NOT NULL,
                                      "Nationality" character varying(50) NOT NULL,
                                      "PostalAddress" character varying(255) NOT NULL,
                                      "PassportNumber" character varying(20) NOT NULL,
                                      "DateOfExpiry" timestamp with time zone NOT NULL,
                                      "IsPrevious" boolean NOT NULL,
                                      "Id" integer NOT NULL
);


ALTER TABLE public."SpouseInfos" OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 18414)
-- Name: SpouseInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."SpouseInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SpouseInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 18470)
-- Name: Statuses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Statuses" (
                                   "Id" integer NOT NULL,
                                   "Reason" text,
                                   "Flag" text,
                                   "Status" text,
                                   "AdminId" integer NOT NULL
);


ALTER TABLE public."Statuses" OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 18469)
-- Name: Statuses_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Statuses" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Statuses_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 18253)
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
                               "UserID" integer NOT NULL,
                               "FirstName" text NOT NULL,
                               "LastName" text NOT NULL,
                               "AccountVerified" integer NOT NULL,
                               "MobileNumber" text NOT NULL,
                               "Email" text NOT NULL,
                               "Password" text NOT NULL,
                               "OldPassword" text[]
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 18261)
-- Name: UserInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."UserInfos" (
                                    "Id" integer NOT NULL,
                                    "FullName" character varying(100) NOT NULL,
                                    "Nationality" character varying(50),
                                    "Gender" character varying(10),
                                    "DOB" timestamp with time zone NOT NULL,
                                    "BirthCountry" text,
                                    "BirthPlace" text,
                                    "Height" integer NOT NULL,
                                    "Peculiarity" character varying(255) NOT NULL,
                                    "DomicileAddress" character varying(255) NOT NULL,
                                    "AddressDuringSriLanka" character varying(255) NOT NULL,
                                    "Telephone" character varying(20) NOT NULL,
                                    "Mobile" character varying(20) NOT NULL,
                                    "Email" character varying(100) NOT NULL,
                                    "CivilStatus" integer NOT NULL,
                                    "UserID" integer NOT NULL,
                                    "Image" text DEFAULT ''::text NOT NULL,
                                    "Periodofvisit" integer DEFAULT 0 NOT NULL,
                                    "CreatedAt" timestamp with time zone,
                                    "StatusId" integer
);


ALTER TABLE public."UserInfos" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 18260)
-- Name: UserInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."UserInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 18252)
-- Name: User_UserID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ALTER COLUMN "UserID" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_UserID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 18369)
-- Name: VisaExtensionInfos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."VisaExtensionInfos" (
                                             "Id" integer NOT NULL,
                                             "PeriodVisaRequiredFor" character varying(100) NOT NULL,
                                             "ExtentVisaRequiredFor" character varying(50) NOT NULL,
                                             "CurrencyType" text NOT NULL,
                                             "Amount" numeric NOT NULL,
                                             "AmountCashed" numeric NOT NULL,
                                             "ExchangeBroughtIn" numeric NOT NULL,
                                             "CreditCardAvailable" boolean NOT NULL,
                                             "EntryVisaInfoId" integer NOT NULL
);


ALTER TABLE public."VisaExtensionInfos" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 18368)
-- Name: VisaExtensionInfos_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."VisaExtensionInfos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."VisaExtensionInfos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 18247)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
                                                "MigrationId" character varying(150) NOT NULL,
                                                "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3529 (class 0 OID 18484)
-- Dependencies: 247
-- Data for Name: Admins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Admins" ("AdminId", "Email", "Name", "Password") FROM stdin;
\.


--
-- TOC entry 3520 (class 0 OID 18382)
-- Dependencies: 238
-- Data for Name: Businesses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Businesses" ("Id", "NameOfBusiness", "AddressOfBusiness", "RegistrationNumber", "SharesOwned", "ResidenceVisaInfoId") FROM stdin;
\.


--
-- TOC entry 3503 (class 0 OID 18269)
-- Dependencies: 221
-- Data for Name: Childrens; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Childrens" ("Id", "Name", "Gender", "PlaceOfBirth", "UserInfoId") FROM stdin;
\.


--
-- TOC entry 3505 (class 0 OID 18282)
-- Dependencies: 223
-- Data for Name: EmergencyContacts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EmergencyContacts" ("Id", "Name", "Address", "Contact", "Relationship", "UserInfoId", "SpendableAmount", "Support", "UsdAmount", "nameOfCreditCard") FROM stdin;
\.


--
-- TOC entry 3516 (class 0 OID 18358)
-- Dependencies: 234
-- Data for Name: EntryVisaApprovals; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EntryVisaApprovals" ("Id", "VisaNumber", "DateIssued", "Purpose", "EntryVisaInfoId") FROM stdin;
\.


--
-- TOC entry 3507 (class 0 OID 18293)
-- Dependencies: 225
-- Data for Name: EntryVisaInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EntryVisaInfos" ("Id", "ObjectOfVisit", "ModeOfTravel", "DateOfLeaving", "LastPlaceOfResidence", "DateOfIssue", "ResidenceVisaNumber", "HasRefusedVisa", "UserInfoId", "LastObtainedVisa", "PeriodOfValidity", "PeriodOfVisitVisa") FROM stdin;
\.


--
-- TOC entry 3508 (class 0 OID 18303)
-- Dependencies: 226
-- Data for Name: NaturalizationInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."NaturalizationInfos" ("UserInfoId", "IsNaturalized", "NaturalizationDate", "PlaceOfNaturalization", "FormerNationality", id) FROM stdin;
\.


--
-- TOC entry 3509 (class 0 OID 18313)
-- Dependencies: 227
-- Data for Name: Passports; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Passports" ("UserInfoId", "Number", "PlaceOfIssue", "DateOfIssue", "DateOfExpiry", "Id", "PreviousDateOfExpiry", "PreviousDateOfIssue", "PreviousNumber", "PreviousPlaceOfIssue") FROM stdin;
\.


--
-- TOC entry 3511 (class 0 OID 18324)
-- Dependencies: 229
-- Data for Name: Professions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Professions" ("Id", "NameOfWorkplace", "AddressOfWorkplace", "Email", "Fax", "UserInfoId") FROM stdin;
\.


--
-- TOC entry 3522 (class 0 OID 18395)
-- Dependencies: 240
-- Data for Name: ResidenceVisaApprovals; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ResidenceVisaApprovals" ("Id", "VisaNumber", "DateIssued", "Purpose", "ResidenceVisaInfoId") FROM stdin;
\.


--
-- TOC entry 3513 (class 0 OID 18335)
-- Dependencies: 231
-- Data for Name: ResidenceVisaInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ResidenceVisaInfos" ("Id", "DateOfArrival", "ReasonForApplyingVisa", "ApplyingFor", "SalaryIncome", "UserInfoId") FROM stdin;
\.


--
-- TOC entry 3514 (class 0 OID 18347)
-- Dependencies: 232
-- Data for Name: SpouseInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."SpouseInfos" ("UserInfoId", "Fullname", "Nationality", "PostalAddress", "PassportNumber", "DateOfExpiry", "IsPrevious", "Id") FROM stdin;
\.


--
-- TOC entry 3527 (class 0 OID 18470)
-- Dependencies: 245
-- Data for Name: Statuses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Statuses" ("Id", "Reason", "Flag", "Status", "AdminId") FROM stdin;
\.


--
-- TOC entry 3499 (class 0 OID 18253)
-- Dependencies: 217
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."User" ("UserID", "FirstName", "LastName", "AccountVerified", "MobileNumber", "Email", "Password", "OldPassword") FROM stdin;
\.


--
-- TOC entry 3501 (class 0 OID 18261)
-- Dependencies: 219
-- Data for Name: UserInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."UserInfos" ("Id", "FullName", "Nationality", "Gender", "DOB", "BirthCountry", "BirthPlace", "Height", "Peculiarity", "DomicileAddress", "AddressDuringSriLanka", "Telephone", "Mobile", "Email", "CivilStatus", "UserID", "Image", "Periodofvisit", "CreatedAt", "StatusId") FROM stdin;
\.


--
-- TOC entry 3518 (class 0 OID 18369)
-- Dependencies: 236
-- Data for Name: VisaExtensionInfos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."VisaExtensionInfos" ("Id", "PeriodVisaRequiredFor", "ExtentVisaRequiredFor", "CurrencyType", "Amount", "AmountCashed", "ExchangeBroughtIn", "CreditCardAvailable", "EntryVisaInfoId") FROM stdin;
\.


--
-- TOC entry 3497 (class 0 OID 18247)
-- Dependencies: 215
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20240904212431_allmodels	8.0.8
20240905091159_modelsnew	8.0.8
20240905100046_modelsnew2	8.0.8
20240905223200_dbform2	8.0.8
20240906053203_structureddb	8.0.8
20240906054010_dbfinal	8.0.8
20240906073535_dbfinal-1	8.0.8
20240906121839_db5pm	8.0.8
\.


--
-- TOC entry 3535 (class 0 OID 0)
-- Dependencies: 246
-- Name: Admins_AdminId_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Admins_AdminId_seq"', 1, false);


--
-- TOC entry 3536 (class 0 OID 0)
-- Dependencies: 237
-- Name: Businesses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Businesses_Id_seq"', 1, false);


--
-- TOC entry 3537 (class 0 OID 0)
-- Dependencies: 220
-- Name: Childrens_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Childrens_Id_seq"', 1, false);


--
-- TOC entry 3538 (class 0 OID 0)
-- Dependencies: 222
-- Name: EmergencyContacts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EmergencyContacts_Id_seq"', 1, false);


--
-- TOC entry 3539 (class 0 OID 0)
-- Dependencies: 233
-- Name: EntryVisaApprovals_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EntryVisaApprovals_Id_seq"', 1, false);


--
-- TOC entry 3540 (class 0 OID 0)
-- Dependencies: 224
-- Name: EntryVisaInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EntryVisaInfos_Id_seq"', 1, false);


--
-- TOC entry 3541 (class 0 OID 0)
-- Dependencies: 243
-- Name: NaturalizationInfos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."NaturalizationInfos_id_seq"', 1, false);


--
-- TOC entry 3542 (class 0 OID 0)
-- Dependencies: 242
-- Name: Passports_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Passports_Id_seq"', 1, false);


--
-- TOC entry 3543 (class 0 OID 0)
-- Dependencies: 228
-- Name: Professions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Professions_Id_seq"', 1, false);


--
-- TOC entry 3544 (class 0 OID 0)
-- Dependencies: 239
-- Name: ResidenceVisaApprovals_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ResidenceVisaApprovals_Id_seq"', 1, false);


--
-- TOC entry 3545 (class 0 OID 0)
-- Dependencies: 230
-- Name: ResidenceVisaInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ResidenceVisaInfos_Id_seq"', 1, false);


--
-- TOC entry 3546 (class 0 OID 0)
-- Dependencies: 241
-- Name: SpouseInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."SpouseInfos_Id_seq"', 1, false);


--
-- TOC entry 3547 (class 0 OID 0)
-- Dependencies: 244
-- Name: Statuses_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Statuses_Id_seq"', 1, false);


--
-- TOC entry 3548 (class 0 OID 0)
-- Dependencies: 218
-- Name: UserInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."UserInfos_Id_seq"', 1, false);


--
-- TOC entry 3549 (class 0 OID 0)
-- Dependencies: 216
-- Name: User_UserID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."User_UserID_seq"', 1, false);


--
-- TOC entry 3550 (class 0 OID 0)
-- Dependencies: 235
-- Name: VisaExtensionInfos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."VisaExtensionInfos_Id_seq"', 1, false);


--
-- TOC entry 3340 (class 2606 OID 18490)
-- Name: Admins PK_Admins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Admins"
    ADD CONSTRAINT "PK_Admins" PRIMARY KEY ("AdminId");


--
-- TOC entry 3333 (class 2606 OID 18388)
-- Name: Businesses PK_Businesses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Businesses"
    ADD CONSTRAINT "PK_Businesses" PRIMARY KEY ("Id");


--
-- TOC entry 3303 (class 2606 OID 18275)
-- Name: Childrens PK_Childrens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Childrens"
    ADD CONSTRAINT "PK_Childrens" PRIMARY KEY ("Id");


--
-- TOC entry 3306 (class 2606 OID 18286)
-- Name: EmergencyContacts PK_EmergencyContacts; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EmergencyContacts"
    ADD CONSTRAINT "PK_EmergencyContacts" PRIMARY KEY ("Id");


--
-- TOC entry 3327 (class 2606 OID 18362)
-- Name: EntryVisaApprovals PK_EntryVisaApprovals; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EntryVisaApprovals"
    ADD CONSTRAINT "PK_EntryVisaApprovals" PRIMARY KEY ("Id");


--
-- TOC entry 3309 (class 2606 OID 18297)
-- Name: EntryVisaInfos PK_EntryVisaInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EntryVisaInfos"
    ADD CONSTRAINT "PK_EntryVisaInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3312 (class 2606 OID 18431)
-- Name: NaturalizationInfos PK_NaturalizationInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NaturalizationInfos"
    ADD CONSTRAINT "PK_NaturalizationInfos" PRIMARY KEY (id);


--
-- TOC entry 3315 (class 2606 OID 18429)
-- Name: Passports PK_Passports; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Passports"
    ADD CONSTRAINT "PK_Passports" PRIMARY KEY ("Id");


--
-- TOC entry 3318 (class 2606 OID 18328)
-- Name: Professions PK_Professions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Professions"
    ADD CONSTRAINT "PK_Professions" PRIMARY KEY ("Id");


--
-- TOC entry 3336 (class 2606 OID 18399)
-- Name: ResidenceVisaApprovals PK_ResidenceVisaApprovals; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ResidenceVisaApprovals"
    ADD CONSTRAINT "PK_ResidenceVisaApprovals" PRIMARY KEY ("Id");


--
-- TOC entry 3321 (class 2606 OID 18341)
-- Name: ResidenceVisaInfos PK_ResidenceVisaInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ResidenceVisaInfos"
    ADD CONSTRAINT "PK_ResidenceVisaInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3324 (class 2606 OID 18427)
-- Name: SpouseInfos PK_SpouseInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SpouseInfos"
    ADD CONSTRAINT "PK_SpouseInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3338 (class 2606 OID 18476)
-- Name: Statuses PK_Statuses; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Statuses"
    ADD CONSTRAINT "PK_Statuses" PRIMARY KEY ("Id");


--
-- TOC entry 3297 (class 2606 OID 18259)
-- Name: User PK_User; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "PK_User" PRIMARY KEY ("UserID");


--
-- TOC entry 3300 (class 2606 OID 18267)
-- Name: UserInfos PK_UserInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserInfos"
    ADD CONSTRAINT "PK_UserInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3330 (class 2606 OID 18375)
-- Name: VisaExtensionInfos PK_VisaExtensionInfos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."VisaExtensionInfos"
    ADD CONSTRAINT "PK_VisaExtensionInfos" PRIMARY KEY ("Id");


--
-- TOC entry 3295 (class 2606 OID 18251)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3331 (class 1259 OID 18405)
-- Name: IX_Businesses_ResidenceVisaInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Businesses_ResidenceVisaInfoId" ON public."Businesses" USING btree ("ResidenceVisaInfoId");


--
-- TOC entry 3301 (class 1259 OID 18406)
-- Name: IX_Childrens_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Childrens_UserInfoId" ON public."Childrens" USING btree ("UserInfoId");


--
-- TOC entry 3304 (class 1259 OID 18407)
-- Name: IX_EmergencyContacts_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EmergencyContacts_UserInfoId" ON public."EmergencyContacts" USING btree ("UserInfoId");


--
-- TOC entry 3325 (class 1259 OID 18408)
-- Name: IX_EntryVisaApprovals_EntryVisaInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EntryVisaApprovals_EntryVisaInfoId" ON public."EntryVisaApprovals" USING btree ("EntryVisaInfoId");


--
-- TOC entry 3307 (class 1259 OID 18409)
-- Name: IX_EntryVisaInfos_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EntryVisaInfos_UserInfoId" ON public."EntryVisaInfos" USING btree ("UserInfoId");


--
-- TOC entry 3310 (class 1259 OID 18434)
-- Name: IX_NaturalizationInfos_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_NaturalizationInfos_UserInfoId" ON public."NaturalizationInfos" USING btree ("UserInfoId");


--
-- TOC entry 3313 (class 1259 OID 18433)
-- Name: IX_Passports_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Passports_UserInfoId" ON public."Passports" USING btree ("UserInfoId");


--
-- TOC entry 3316 (class 1259 OID 18410)
-- Name: IX_Professions_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Professions_UserInfoId" ON public."Professions" USING btree ("UserInfoId");


--
-- TOC entry 3334 (class 1259 OID 18411)
-- Name: IX_ResidenceVisaApprovals_ResidenceVisaInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ResidenceVisaApprovals_ResidenceVisaInfoId" ON public."ResidenceVisaApprovals" USING btree ("ResidenceVisaInfoId");


--
-- TOC entry 3319 (class 1259 OID 18412)
-- Name: IX_ResidenceVisaInfos_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_ResidenceVisaInfos_UserInfoId" ON public."ResidenceVisaInfos" USING btree ("UserInfoId");


--
-- TOC entry 3322 (class 1259 OID 18432)
-- Name: IX_SpouseInfos_UserInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_SpouseInfos_UserInfoId" ON public."SpouseInfos" USING btree ("UserInfoId");


--
-- TOC entry 3298 (class 1259 OID 18477)
-- Name: IX_UserInfos_StatusId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_UserInfos_StatusId" ON public."UserInfos" USING btree ("StatusId");


--
-- TOC entry 3328 (class 1259 OID 18413)
-- Name: IX_VisaExtensionInfos_EntryVisaInfoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_VisaExtensionInfos_EntryVisaInfoId" ON public."VisaExtensionInfos" USING btree ("EntryVisaInfoId");


--
-- TOC entry 3352 (class 2606 OID 18389)
-- Name: Businesses FK_Businesses_ResidenceVisaInfos_ResidenceVisaInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Businesses"
    ADD CONSTRAINT "FK_Businesses_ResidenceVisaInfos_ResidenceVisaInfoId" FOREIGN KEY ("ResidenceVisaInfoId") REFERENCES public."ResidenceVisaInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3342 (class 2606 OID 18276)
-- Name: Childrens FK_Childrens_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Childrens"
    ADD CONSTRAINT "FK_Childrens_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3343 (class 2606 OID 18287)
-- Name: EmergencyContacts FK_EmergencyContacts_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EmergencyContacts"
    ADD CONSTRAINT "FK_EmergencyContacts_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3350 (class 2606 OID 18363)
-- Name: EntryVisaApprovals FK_EntryVisaApprovals_EntryVisaInfos_EntryVisaInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EntryVisaApprovals"
    ADD CONSTRAINT "FK_EntryVisaApprovals_EntryVisaInfos_EntryVisaInfoId" FOREIGN KEY ("EntryVisaInfoId") REFERENCES public."EntryVisaInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3344 (class 2606 OID 18298)
-- Name: EntryVisaInfos FK_EntryVisaInfos_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EntryVisaInfos"
    ADD CONSTRAINT "FK_EntryVisaInfos_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3345 (class 2606 OID 18308)
-- Name: NaturalizationInfos FK_NaturalizationInfos_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."NaturalizationInfos"
    ADD CONSTRAINT "FK_NaturalizationInfos_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3346 (class 2606 OID 18318)
-- Name: Passports FK_Passports_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Passports"
    ADD CONSTRAINT "FK_Passports_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3347 (class 2606 OID 18329)
-- Name: Professions FK_Professions_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Professions"
    ADD CONSTRAINT "FK_Professions_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3353 (class 2606 OID 18400)
-- Name: ResidenceVisaApprovals FK_ResidenceVisaApprovals_ResidenceVisaInfos_ResidenceVisaInfo~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ResidenceVisaApprovals"
    ADD CONSTRAINT "FK_ResidenceVisaApprovals_ResidenceVisaInfos_ResidenceVisaInfo~" FOREIGN KEY ("ResidenceVisaInfoId") REFERENCES public."ResidenceVisaInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3348 (class 2606 OID 18342)
-- Name: ResidenceVisaInfos FK_ResidenceVisaInfos_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ResidenceVisaInfos"
    ADD CONSTRAINT "FK_ResidenceVisaInfos_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3349 (class 2606 OID 18352)
-- Name: SpouseInfos FK_SpouseInfos_UserInfos_UserInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SpouseInfos"
    ADD CONSTRAINT "FK_SpouseInfos_UserInfos_UserInfoId" FOREIGN KEY ("UserInfoId") REFERENCES public."UserInfos"("Id") ON DELETE CASCADE;


--
-- TOC entry 3341 (class 2606 OID 18478)
-- Name: UserInfos FK_UserInfos_Statuses_StatusId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."UserInfos"
    ADD CONSTRAINT "FK_UserInfos_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES public."Statuses"("Id");


--
-- TOC entry 3351 (class 2606 OID 18376)
-- Name: VisaExtensionInfos FK_VisaExtensionInfos_EntryVisaInfos_EntryVisaInfoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."VisaExtensionInfos"
    ADD CONSTRAINT "FK_VisaExtensionInfos_EntryVisaInfos_EntryVisaInfoId" FOREIGN KEY ("EntryVisaInfoId") REFERENCES public."EntryVisaInfos"("Id") ON DELETE CASCADE;


-- Completed on 2024-09-06 17:50:13 +0530

--
-- PostgreSQL database dump complete
--

