networks:
  dcodenetwork:
    driver: bridge

services:
  postgres:
    image: postgres:13
    container_name: dcode-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: docdeDB
    networks:
      - dcodenetwork
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5002:5432"

  auth-api:
    build:
      context: .
      dockerfile: ./AuthAPI/Dockerfile
    container_name: CS-auth-api
    image: ${DOCKER_REGISTRY-}auth-api
    environment:
      DATABASE_URL: "Host=postgres;Port=5432;Database=docdeDB;Username=postgres;Password=123;"
    networks:
      - dcodenetwork
    depends_on:
      - postgres
    ports:
      - "5001:8080"
    command: >
      bash -c "until dotnet ef database update; do echo 'Waiting for postgres...'; sleep 5; done && dotnet AuthAPI.dll"

  visa-api:
    build:
      context: .
      dockerfile: ./VisaAPI/Dockerfile
    container_name: CS-visa-api
    image: ${DOCKER_REGISTRY-}visa-api
    environment:
      DATABASE_URL: "Host=postgres;Port=5432;Database=docdeDB;Username=postgres;Password=123;"
    networks:
      - dcodenetwork
    depends_on:
      - postgres
    ports:
      - "5003:8080"  # Changed to avoid port conflict with auth-api
    command: >
      dotnet VisaAPI.dll  # Removed migration logic

  gateway:
    build:
      context: .
      dockerfile: ./Gateway/Dockerfile
    container_name: dcode-gateway
    image: ${DOCKER_REGISTRY-}gateway
    networks:
      - dcodenetwork
    depends_on:
      - auth-api
      - visa-api
    ports:
      - "5000:8080"
